import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const Colors = {
  bgTop: '#2E6DFF',
  bgMid: '#2350B5',
  bgBottom: '#0F3C8A',
  cardTop: '#5EA1FF',
  cardBottom: '#3D75FF',
  chip: '#2C5BEA',
  white: '#FFFFFF',
  textPrimary: 'rgba(255,255,255,0.95)',
  textSecondary: 'rgba(255,255,255,0.7)',
  tickGreen: '#27D17F',
  badgeBlue: '#4C8DFF',
  badgeBorder: '#0E2E72',
  recordRed: '#FF3B30',
  inviteStart: '#79A8FF',
  inviteEnd: '#497BFF',
  readyStart: '#FFC857',
  readyEnd: '#FF9D2E',
  chatName: '#F6D365',
  panel: 'rgba(0,0,0,0.15)',
  pill: 'rgba(255,255,255,0.1)',
  gearHalo: 'rgba(255, 215, 0, 0.3)',
  pinBolt: '#8EC3FF',
  counterOrange: '#FFA12D',
};

export const FontWeights = {
  regular: '400' as const,
  medium: '600' as const,
  bold: '700' as const,
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  xxxl: 32,
};

export const BorderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 28,
  full: 999,
};

export const Sizes = {
  contentMaxWidth: 420,
  contentPadding: 10,
  headerCardWidth: 0.76,
  headerCardMinWidth: 280,
  headerCardHeight: 86,
  seatOuter: 66,
  seatInner: 60,
  badge: 20,
  recordingBubble: 48,
  micCircle: 30,
  primaryButtonHeight: 56,
  primaryButtonMaxWidth: 180,
  primaryButtonMinWidth: 180,
  chatPanelMinHeight: 260,
  toolbarHeight: 82,
  toolbarButton: 52,
  toolbarIcon: 26,
  gridGap: 0,
};

export const Shadows = {
  card: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
  },
  seat: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  toolbarButton: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  fill: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: Sizes.contentPadding,
    maxWidth: Sizes.contentMaxWidth,
    alignSelf: 'center',
    width: '100%',
  },
  headerCard: {
    width: `${Sizes.headerCardWidth * 100}%`,
    minWidth: Sizes.headerCardMinWidth,
    height: Sizes.headerCardHeight,
    alignSelf: 'center',
    marginTop: Spacing.lg,
    borderRadius: BorderRadius.lg,
    ...Shadows.card,
    position: 'relative',
  },
  headerCardInner: {
    flex: 1,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: FontWeights.medium,
    color: Colors.white,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  headerSubtitle: {
    fontSize: 15,
    fontWeight: FontWeights.medium,
    color: Colors.white,
    backgroundColor: Colors.chip,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: BorderRadius.md,
    overflow: 'hidden',
  },
  playersGrid: {
    marginTop: Spacing.md,
    paddingHorizontal: 0,
  },
  playerSeat: {
    width: Sizes.seatOuter,
    height: Sizes.seatOuter + 40, // Extra height for name labels
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 0,
  },
  avatar: {
    width: Sizes.seatInner,
    height: Sizes.seatInner,
    borderRadius: Sizes.seatInner / 2,
    ...Shadows.seat,
  },
  seatBadge: {
    position: 'absolute',
    left: 0,
    top: -4,
    width: Sizes.badge,
    height: Sizes.badge,
    borderRadius: Sizes.badge / 2,
    backgroundColor: Colors.badgeBlue,
    borderWidth: 2,
    borderColor: Colors.badgeBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seatBadgeRight: {
    position: 'absolute',
    right: 0,
    top: -4,
    width: Sizes.badge,
    height: Sizes.badge,
    borderRadius: Sizes.badge / 2,
    backgroundColor: Colors.badgeBlue,
    borderWidth: 2,
    borderColor: Colors.badgeBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  seatBadgeText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: FontWeights.bold,
  },
  readyTick: {
    position: 'absolute',
    right: 0,
    top: -2,
    width: Sizes.badge,
    height: Sizes.badge,
    borderRadius: Sizes.badge / 2,
    backgroundColor: Colors.tickGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readyTickLeft: {
    position: 'absolute',
    left: 0,
    top: -2,
    width: Sizes.badge,
    height: Sizes.badge,
    borderRadius: Sizes.badge / 2,
    backgroundColor: Colors.tickGreen,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deadCross: {
    position: 'absolute',
    right: 0,
    top: -2,
    width: Sizes.badge,
    height: Sizes.badge,
    borderRadius: Sizes.badge / 2,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FF3B30',
  },
  deadCrossLeft: {
    position: 'absolute',
    left: 0,
    top: -2,
    width: Sizes.badge,
    height: Sizes.badge,
    borderRadius: Sizes.badge / 2,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FF3B30',
  },
  playerName: {
    fontSize: 12,
    color: Colors.textPrimary,
    textAlign: 'center',
    marginTop: Spacing.xs,
    maxWidth: Sizes.seatOuter + 20,
  },
  playerNameSecondary: {
    fontSize: 12,
    color: Colors.textSecondary,
    textAlign: 'center',
  },
  micButton: {
    position: 'absolute',
    right: -10,
    top: Sizes.seatOuter / 1.75 - Sizes.micCircle / 100,
    width: Sizes.micCircle,
    height: Sizes.micCircle,
    borderRadius: Sizes.micCircle / 2,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.seat,
  },
  micButtonLeft: {
    position: 'absolute',
    left: -10,
    top: Sizes.seatOuter / 1.75 - Sizes.micCircle / 100,
    width: Sizes.micCircle,
    height: Sizes.micCircle,
    borderRadius: Sizes.micCircle / 2,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.seat,
  },
  voteAvatarsRight: {
    position: 'absolute',
    right: -15,
    top: Sizes.seatOuter / 2 - 12,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
  },
  voteAvatarsLeft: {
    position: 'absolute',
    left: -15,
    top: Sizes.seatOuter / 2 - 12,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
  },
  recordingBubble: {
    position: 'absolute',
    right: -24,
    top: Sizes.seatOuter / 2 - Sizes.recordingBubble / 2,
    width: Sizes.recordingBubble,
    height: Sizes.recordingBubble,
    borderRadius: Sizes.recordingBubble / 2,
    backgroundColor: Colors.recordRed,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadows.seat,
  },
  recordingInner: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.white,
  },
  counterBadge: {
    position: 'absolute',
    right: -6,
    top: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: Colors.counterOrange,
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: FontWeights.bold,
  },
  primaryActions: {
    position: 'absolute',
    top: "50%",
    transform: [{ translateY: -Sizes.primaryButtonHeight / 2 }],
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: Spacing.lg,
  },
  primaryButton: {
    width: '100%',
    maxWidth: Sizes.primaryButtonMaxWidth,
    minWidth: Sizes.primaryButtonMinWidth,
    height: Sizes.primaryButtonHeight,
    borderRadius: BorderRadius.xxl,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.xs,
  },
  primaryButtonText: {
    fontSize: 17,
    fontWeight: FontWeights.bold,
    color: Colors.white,
    textTransform: 'uppercase',
  },
  chatPanel: {
    flex: 1,
    minHeight: Sizes.chatPanelMinHeight,
    marginBottom: Spacing.lg,
    backgroundColor: Colors.panel,
    borderRadius: BorderRadius.lg,
    padding: 14,
  },
  chatMessage: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: Spacing.sm,
  },
  chatAvatar: {
    fontSize: 16,
    marginRight: Spacing.xs,
  },
  chatName: {
    fontSize: 13,
    fontWeight: FontWeights.bold,
    color: Colors.chatName,
    marginRight: Spacing.xs,
  },
  chatText: {
    fontSize: 13,
    color: Colors.white,
    flex: 1,
  },
  bottomToolbar: {
    height: Sizes.toolbarHeight,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
    paddingBottom: Spacing.lg,
    paddingTop: Spacing.xxl,
  },
  toolbarButton: {
    width: Sizes.toolbarButton,
    height: Sizes.toolbarButton,
    borderRadius: Sizes.toolbarButton / 2,
    backgroundColor: Colors.pill,
    alignItems: 'center',
    justifyContent: 'center',
    // ...Shadows.toolbarButton,
  },
  gearHalo: {
    position: 'absolute',
    width: 140,
    height: 140,
    alignSelf: 'center',
    top: -20,
    opacity: 0.2,
    zIndex: -1,
  },
  pinBolt: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.pinBolt,
  },
  pinBoltLeft: {
    left: -3,
    top: -3,
  },
  pinBoltRight: {
    right: -3,
    top: -3,
  },
  // Additional styles needed for the current implementation
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    paddingTop: 20,
    paddingBottom: 0,
  },
  headerIcon: {
    padding: 8,
  },
  roomInfoCard: {
    backgroundColor: '#4A90E2',
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    position: 'relative',
  },
  screwContainer: {
    position: 'absolute',
    top: -4,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
  },
  screw: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#C0C0C0',
    borderWidth: 1,
    borderColor: '#A0A0A0',
  },
  roomName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 2,
  },
  gameName: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.9,
  },
  headerRightIcons: {
    flexDirection: 'row',
    gap: 10,
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  timerText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 15,
    gap: 4,
  },
  connectionText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '500',
  },
  roundContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  roundText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: Colors.panel,
    borderRadius: BorderRadius.lg,
    padding: Spacing.xxl,
    alignItems: 'center',
    minWidth: 280,
    maxWidth: 320,
    ...Shadows.card,
  },
  modalContent: {
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: FontWeights.bold,
    color: Colors.white,
    textAlign: 'center',
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  modalSubtitle: {
    fontSize: 16,
    color: Colors.textSecondary,
    textAlign: 'center',
    marginBottom: Spacing.md,
  },
  modalWord: {
    fontSize: 32,
    fontWeight: FontWeights.bold,
    color: Colors.chatName,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  modalCountdown: {
    fontSize: 48,
    fontWeight: FontWeights.bold,
    color: Colors.readyStart,
    textAlign: 'center',
    marginTop: Spacing.lg,
  },
  modalButton: {
    backgroundColor: Colors.readyStart,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.md,
    marginTop: Spacing.lg,
  },
  modalButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: FontWeights.medium,
    textAlign: 'center',
  },
  // Chat input area styles
  chatInputArea: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#1A1A1A',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    gap: Spacing.sm,
  },
  chatInputField: {
    flex: 1,
    color: Colors.white,
    fontSize: 16,
    maxHeight: 100,
    minHeight: 40,
    textAlignVertical: 'top',
  },
  sendChatButton: {
    backgroundColor: Colors.badgeBlue,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wordDisplayContainer: {
    position: 'absolute',
    top: screenHeight * 0.14, // 15% from top of screen
    left: 0,
    right: 0,
    zIndex: 10,
    paddingHorizontal: Spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wordDisplayLabel: {
    color: Colors.white, // White color for "Your Word:"
    fontSize: screenWidth < 400 ? 14 : 16, // Responsive font size
    fontWeight: FontWeights.medium,
    textAlign: 'center',
  },
  wordDisplayText: {
    color: Colors.readyStart, // Yellow/gold color for the actual word
    fontSize: screenWidth < 400 ? 20 : 24, // Increased font size
    fontWeight: FontWeights.bold,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 3,
  },
  playersGridContainer: {
    position: 'relative',
  },
  speakerDisplayContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -screenWidth * 0.2 }, { translateY: -15 }],
    zIndex: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  speakerDisplayText: {
    color: Colors.white,
    fontSize: screenWidth < 400 ? 14 : 16,
    fontWeight: FontWeights.bold,
    textAlign: 'center',
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.lg,
    // borderWidth: 1,
    borderColor: Colors.textPrimary,
    maxWidth: screenWidth * 0.55, // 85% of screen width
    minWidth: screenWidth * 0.4, // Minimum 50% of screen width
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: Spacing.lg,
    textShadowColor: 'rgba(0,0,0,0.8)',
    textShadowOffset: {
      width: 1,
      height: 1,
    },
    textShadowRadius: 2,
  },
});
